DjangoBeltReviewer/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from apps.users import views as users_views
urlpatterns = [
    url(r'^$', users_views.index),
    url(r'^users/', include('apps.users.urls', namespace = 'users')),
    url(r'^books/', include('apps.books.urls', namespace = 'books'))
]

apps/books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^process_book$', views.process_book, name='process_book'),
    url(r'^(?P<id>[0-9]+)/$', views.display_book, name='display_book'),
    url(r'^delete_review/(?P<id>[0-9]+)/$', views.delete_review, name='delete_review')
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^(?P<id>[0-9]+)/$', views.user, name='user')
]

apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def basic_validator(self, request):
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        pw = request.POST['pw']
        pw_confirm = request.POST['pw_confirm']

        request.session['first_name'] = first_name
        request.session['last_name'] = last_name
        request.session['email'] = email

        errors = {}
        if len(first_name) < 2 or len(last_name) < 2 or not first_name.isalpha() or not last_name.isalpha():
            errors['names'] = 'First and last names must be at least 2 characters and only contain letters!'
        
        if len(email) < 1:
            errors['email'] = 'Email cannot be blank!'
        elif not EMAIL_REGEX.match(email):
            errors['email'] = 'Invalid email address!'
        
        if len(pw) < 8:
            errors['pw'] = 'Password must be at least 8 characters!'
        
        if pw != pw_confirm:
            errors['pw_confirm'] = 'Passwords don\'t match!'

        return errors

class BookManager(models.Manager):
    def book_validator(self, request):
        book_title = request.POST['book_title']
        request.session['book_title'] = book_title

        errors = {}
        if len(book_title) < 1:
            errors['book_title'] = 'Book title cannot be blank!'

        if request.POST['author_name_list'] == 'custom':
            author_name = request.POST['author_name']
            request.session['author_name'] = author_name
            if len(author_name) < 2:
                errors['author_name'] = 'Author name must be at least 2 characters!'

        return errors

class ReviewManager(models.Manager):
    def review_validator(self, request):
        review = request.POST['review']
        request.session['review'] = review

        errors = {}
        if len(review) < 1:
            errors['review'] = 'Review cannot be blank!'
        return errors

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    objects = UserManager()
    pw = models.CharField(max_length=255)
    def __repr__(self):
        return "<User object: {} {}>".format(self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=255)
    author_name = models.CharField(max_length=255)
    users = models.ManyToManyField(User, related_name="books")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()
    def __repr__(self):
        return "<Book object: {}>".format(self.title)

class Review(models.Model):
    review = models.TextField()
    rating = models.PositiveSmallIntegerField()
    book = models.ForeignKey(Book, related_name="reviews")
    user = models.ForeignKey(User, related_name="reviews")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ReviewManager()
    def __repr__(self):
        return "<Review object: {}>".format(self.book)

apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.core.urlresolvers import reverse

import bcrypt

from .models import User

def index(request):
    if 'id' in request.session:
        return redirect(reverse('books:index'))
    if 'first_name' not in request.session:
        request.session['first_name'] = ''
    if 'last_name' not in request.session:
        request.session['last_name'] = ''
    if 'email' not in request.session:
        request.session['email'] = ''
    return render(request, 'users/index.html')

def register(request):
    if request.method == 'POST':
        # FORM VALIDATION
        errors = User.objects.basic_validator(request)
        if len(errors):
            for tag, error in errors.iteritems():
                messages.error(request, error, extra_tags=tag)
            return redirect('/')

        # CHECK IF EMAIL IS ALREADY IN DATABASE
        found_users = User.objects.filter(email=request.POST['email'])
        if found_users.count() > 0:
            messages.error(request, 'Email already taken', extra_tags='email')
            return redirect('/')

        # ADD USER TO DATABASE
        pw_hashed = bcrypt.hashpw(request.POST['pw'].encode(), bcrypt.gensalt())
        new_user_id = User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], pw=pw_hashed).id

        request.session['last_name'] = ''
        request.session['email'] = ''
        request.session['id'] = new_user_id

        return redirect(reverse('books:index'))
    else:
        return redirect('/')

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        pw = request.POST['pw']
        request.session['login_email'] = email

        # FORM VALIDATION
        if len(email) < 1 or len(pw) < 1:
            messages.error(request, 'Email and/or password fields cannot be blank!')
            return redirect('/')
        
        # USER LOGIN
        users = User.objects.filter(email=email)
        if len(users) < 1:
            messages.error(request, 'No user with that email!')
            return redirect(reverse('users:index'))
        for user in users:
            if bcrypt.checkpw(pw.encode(), user.pw.encode()):
                request.session['login_email'] = ''
                request.session['id'] = user.id
                request.session['first_name'] = user.first_name
                return redirect(reverse('books:index'))
        messages.error(request, 'Wrong email/password combination!')
        return redirect('/')
    else:
        return redirect('/')

def logout(request):
    request.session.flush()
    return redirect('/')

def user(request, id):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in to view')
        return redirect('/')
    user = User.objects.get(id=id)
    context = {
        'first_name': user.first_name,
        'last_name': user.last_name,
        'email': user.email,
        'total_reviews': user.reviews.count(),
        'reviews': []
    }
    reviews = user.reviews.all()
    for review in reviews:
        context['reviews'].append({
            'book_id': review.book.id,
            'book_title': review.book.title
        })
    return render(request, 'users/user.html', context)

apps/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Welcome</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        {% if messages %}
        <div style="color:red;">
            <h3>ERRORS:</h3>
            <ul>
                {% for message in messages %}
                <li>{{message}}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <h1>Registration</h1>
         <form action={% url 'users:register' %} method="POST">
            {% csrf_token %}
            <label for="first_name">First Name: </label>
            <input type="text" name="first_name" id="first_name" value="{{request.session.first_name}}">
            <br><br>
            <label for="last_name">Last Name: </label>
            <input type="text" name="last_name" id="last_name" value="{{request.session.last_name}}">
            <br><br>
            <label for="email">Email: </label>
            <input type="text" name="email" id="email" value="{{request.session.email}}">
            <br><br>
            <label for="pw">Password: </label>
            <input type="password" name="pw" id="pw">
            <br><br>
            <label for="pw_confirm">Confirm Password: </label>
            <input type="password" name="pw_confirm" id="pw_confirm">
            <br><br>
            <input type="submit" value="Register">
        </form>

        <h1>Login</h1>
        <form action={% url 'users:login' %} method="POST">
            {% csrf_token %}
            <label for="login_email">Email: </label>
            <input type="text" name="email" id="login_email" value="{{request.session.login_email}}">
            <br><br>
            <label for="login_pw">Password: </label>
            <input type="password" name="pw" id="login_pw">
            <br><br>
            <input type="submit" value="Login">
        </form> 
    </body>
</html>

apps/users/templates/users/user.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>User Reviews</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <p>
            {{request.session.first_name}}: 
            <a href={% url 'books:index' %}>Home</a> | 
            <a href={% url 'books:add' %}>Add Book and Review</a> | 
            <a href={% url 'users:logout' %}>Logout</a>
        </p>
        <h1>User Alias: {{first_name}}</h1>
        <p>Name: {{first_name}} {{last_name}}</p>
        <p>Email: {{email}}</p>
        <p>Total Reviews: {{total_reviews}}</p>
        <p>Posted Reviews on the following books:</p>
        <ul>
        {% for review in reviews %}
            <li>
                <a href={% url 'books:display_book' id=review.book_id %}>{{review.book_title}}</a>
            </li>
        {% endfor %}
        </ul>
    </body>
</html>