DjangoBeltReviewer/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from apps.users import views as users_views
urlpatterns = [
    url(r'^$', users_views.index),
    url(r'^users/', include('apps.users.urls', namespace = 'users')),
    url(r'^books/', include('apps.books.urls', namespace = 'books'))
]

apps/books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^process_book$', views.process_book, name='process_book'),
    url(r'^(?P<id>[0-9]+)/$', views.display_book, name='display_book'),
    url(r'^delete_review/(?P<id>[0-9]+)/$', views.delete_review, name='delete_review')
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^(?P<id>[0-9]+)/$', views.user, name='user')
]

apps/books/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/books/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.core.urlresolvers import reverse

from ..users.models import *

def index(request):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in to view')
        return redirect('/')

    context = {'reviews': [], 'books': []}
    # context['book'] --> 指的是最新被添加的书（要包括书的信息，评论者的信息和评论信息）
    # context['books'] --> 指的是除了最新的三本书之外的书
    books_recent = Book.objects.all().order_by('-updated_at')[:3]
    books3 = []
    for book in books_recent:
        latest_review = book.reviews.first()
        books3.append(book.id)
        context['reviews'].append({
            'book_id': book.id,
            'book_title': book.title,
            'rating': latest_review.rating * '*',
            'user': latest_review.user.first_name,
            'user_id': latest_review.user.id,
            'review': latest_review.review,
            'posted': latest_review.created_at.strftime('%B %d, %Y')
        })
    books = Book.objects.all()
    if len(books) > 3:
        books = Book.objects.all().exclude(id=books3[0]).exclude(id=books3[1]).exclude(id=books3[2]).order_by('title')
        for book in books:
            context['books'].append({
                'book_id': book.id,
                'book_title': book.title
            })
    return render(request, 'books/index.html', context)

def add(request):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in to view')
        return redirect('/')
    if 'book_title' not in request.session:
        request.session['book_title'] = ''
    if 'author_name' not in request.session:
        request.session['author_name'] = ''
    if 'review' not in request.session:
        request.session['review'] = ''
    # context['authors'] --> 是所有书的作者的名字的集合
    context = {'authors': []}
    books = Book.objects.all()
    for book in books:
        context['authors'].append(book.author_name)
    return render(request, 'books/add.html', context)

def process_book(request):
    if request.method == "POST":
        # FORM VALIDATION
        errors_book = Book.objects.book_validator(request)
        if len(errors_book):
            for tag, error in errors_book.iteritems():
                messages.error(request, error, extra_tags=tag)
            return redirect(reverse('books:add'))

        errors_review = Review.objects.review_validator(request)
        if len(errors_review):
            for tag, error in errors_review.iteritems():
                messages.error(request, error, extra_tags=tag)
            return redirect(reverse('books:add'))

        # GATHER INFO
        user_id = request.session['id']
        book_title = request.POST['book_title']
        if request.POST['author_name_list'] == 'custom':
            author_name = request.POST['author_name']
        else:
            author_name = request.POST['author_name_list']
        review = request.POST['review']
        rating = int(request.POST['rating'])

        # CHECK IF BOOK TITLE IS ALREADY IN DATABASE
        books = Book.objects.filter(title=book_title)
        if len(books) < 1:
            new_book = Book.objects.create(title=book_title, author_name=author_name)
        else:
            new_book = books.first()
        book_id = new_book.id

        # ADD BOOK AND REVIEW TO DATABASE
        curr_user = User.objects.get(id=user_id)
        curr_user.books.add(new_book)
        new_review = Review.objects.create(review=review, rating=rating, book=new_book, user=curr_user)
        
        request.session['book_title'] = ''
        request.session['author_name'] = ''
        request.session['review'] = ''
        return redirect(reverse('books:display_book', args=(book_id,)))
    else:
        return redirect(reverse('books:add'))

def display_book(request, id):
    book = Book.objects.get(id=id)
    context = {
        'book_id': int(id),
        'book_title': book.title,
        'author_name': book.author_name,
        'reviews': []
    }
    reviews = Review.objects.filter(book__id=id).order_by('-created_at')
    for review in reviews:
        data = {
            'rating': review.rating * '*',
            'user': review.user.first_name,
            'user_id': review.user.id,
            'review': review.review,
            'review_id': review.id,
            'posted': review.created_at.strftime('%B %d, %Y')
        }
        context['reviews'].append(data)

    return render(request, 'books/book.html', context)

def delete_review(request, id):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in to view')
        return redirect('/')
    review = Review.objects.get(id=id)
    book_id = review.book.id
    review.delete()
    return redirect(reverse('books:display_book', args=(book_id,)))

apps/books/templates/books/add.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Add Book and Review</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        {% if messages %}
        <div style="color:red;">
            <h3>ERRORS:</h3>
            <ul>
                {% for message in messages %}
                <li>{{message}}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <p>
            {{request.session.first_name}}: 
            <a href={% url 'books:index' %}>Home</a> | 
            <a href={% url 'users:logout' %}>Logout</a>
        </p>
        <h1>Add a New Book Title and a Review:</h1>
        <form action={% url 'books:process_book' %} method="POST">
            {% csrf_token %}
            <label for="book_title">Book Title: </label>
            <input type="text" name="book_title" id="book_title" value="{{request.session.book_title}}">
            <br><br>
            Author: <br>
            Choose from the list: 
            <select name="author_name_list">
                <option value="custom">NOT IN LIST</option>
                {% for author in authors %}
                <option value="{{author}}">{{author}}</option>
                {% endfor %}
            </select>
            <br>
            Or add a new author: 
            <input type="text" name="author_name" value="{{request.session.author_name}}">
            <br><br>
            Review: <br>
            <textarea name="review" rows="5" cols="50">{{request.session.review}}</textarea>
            <br><br>
            Rating: 
            <select name="rating">
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select> stars
            <br><br>
            <input type="submit" value="Add Book and Review">
        </form>
    </body>
</html>

apps/books/templates/books/book.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Book Reviews</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <p>
            {{request.session.first_name}}: 
            <a href={% url 'books:index' %}>Home</a> | 
            <a href={% url 'users:logout' %}>Logout</a>
        </p>
        <h2>{{book_title}}</h2>
        <h3>Author: {{author_name}}</h3>
        <h3>Add a Review:</h3>
        <form action={% url 'books:process_book' %} method="POST">
            {% csrf_token %}
            <input type="hidden" name="book_title" value="{{book_title}}">
            <input type="hidden" name="author_name_list" value="custom">
            <input type="hidden" name="author_name" value="{{author_name}}">
            <textarea name="review" rows="5" cols="50"></textarea>
            <br>
            Rating: 
            <select name="rating">
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select> stars
            <br><br>
            <input type="submit" value="Submit Review">
        </form>

        <h1>Reviews:</h1>
        <hr>
        {% for review in reviews %}
        <p>Rating: {{review.rating}}</p>
        <p><a href={% url 'users:user' id=review.user_id %}>{{review.user}}</a> says: {{review.review}}</p>
        <p>Posted on {{review.posted}}</p>
        {% if review.user_id == request.session.id %}
        <p><a href={% url 'books:delete_review' id=review.review_id %}>Delete this Review</a></p>
        {% endif %}
        <hr>
        {% endfor %}
    </body>
</html>

apps/books/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Books Home</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>Welcome, {{request.session.first_name}}!</h1>
        <p>
            <a href={% url 'books:add' %}>Add Book and Review</a> | 
            <a href={% url 'users:logout' %}>Logout</a>
        </p>
        <h2>Recent Book Reviews:</h2>
        {% for review in reviews %}
        <h3><a href={% url 'books:display_book' id=review.book_id %}>{{review.book_title}}</a></h3>
        <p>Rating: {{review.rating}}</p>
        <p>
            <a href={% url 'users:user' id=review.user_id%}>{{review.user}}</a> says: {{review.review}}
        </p>
        <p>Posted on {{review.posted}}</p>
        <br>
        {% endfor %}

        <h2>Other Books with Reviews:</h2>
        <ul>
        {% for book in books %}
            <li>
                <a href={% url 'books:display_book' id=book.book_id %}>{{book.book_title}}</a>
            </li>
        {% endfor %}
        </ul>
    </body>
</html>